--Join consigo relacionar tabelas
-- LEFT (OUTER) JOIN 
-- dois primeiros selects visualização das tabelas que quero usar 
SELECT 
	* 
FROM
	produtos
-------
SELECT 
	* 
FROM 
	SUBCATEGORIA
--------------------------------------
-- No from tem que ser da tabela principal a tabela que quero incluir com informações.
-- após o join fica a tabela que tem as informações complementares.
-- após o on fica tabela da chave estrangeira e depois a tabela onde fica a chave primeira 
SELECT 
	PRODUTOS.ID_PRODUTO,
	PRODUTOS.NOME_PRODUTO,
	PRODUTOS.ID_SUBCATEGORIA,
	SUBCATEGORIA.NOME_SUBCATEGORIA
FROM
	PRODUTOS
	LEFT JOIN SUBCATEGORIA
ON PRODUTOS.ID_SUBCATEGORIA = SUBCATEGORIA.ID_SUBCATEGORIA

--RIGHT (OUTER) JOIN
SELECT 
	* 
FROM
	produtos
-------
SELECT 
	* 
FROM 
	SUBCATEGORIA
------
SELECT 
	PRODUTOS.ID_PRODUTO,
	PRODUTOS.NOME_PRODUTO,
	PRODUTOS.ID_SUBCATEGORIA,
	SUBCATEGORIA.NOME_SUBCATEGORIA
FROM
	PRODUTOS
	RIGHT JOIN SUBCATEGORIA
ON PRODUTOS.ID_CATEGORIA = SUBCATEGORIA.ID_SUBCATEGORIA

-- INNER JOIN
SELECT 
	* 
FROM
	produtos
-------
SELECT 
	* 
FROM 
	SUBCATEGORIA
------
SELECT 
	PRODUTOS.ID_PRODUTO,
	PRODUTOS.NOME_PRODUTO,
	PRODUTOS.ID_SUBCATEGORIA,
	SUBCATEGORIA.NOME_SUBCATEGORIA
FROM
	PRODUTOS
	INNER JOIN SUBCATEGORIA
ON PRODUTOS.ID_CATEGORIA = SUBCATEGORIA.ID_SUBCATEGORIA

--FULL (OUTER) JOIN
SELECT 
	* 
FROM
	produtos
-------
SELECT 
	* 
FROM 
	SUBCATEGORIA
------
SELECT 
	PRODUTOS.ID_PRODUTO,
	PRODUTOS.NOME_PRODUTO,
	PRODUTOS.ID_SUBCATEGORIA,
	SUBCATEGORIA.NOME_SUBCATEGORIA
FROM
	PRODUTOS
FULL JOIN SUBCATEGORIA
ON PRODUTOS.ID_CATEGORIA = SUBCATEGORIA.ID_SUBCATEGORIA

--LEFT (ANTI) JOIN -SE USA RARAMENTE-
SELECT 
	* 
FROM
	produtos
-------
SELECT 
	* 
FROM 
	SUBCATEGORIA
------
SELECT 
	PRODUTOS.ID_PRODUTO,
	PRODUTOS.NOME_PRODUTO,
	PRODUTOS.ID_SUBCATEGORIA,
	SUBCATEGORIA.NOME_SUBCATEGORIA
FROM
	PRODUTOS
LEFT JOIN SUBCATEGORIA
ON PRODUTOS.ID_CATEGORIA = SUBCATEGORIA.ID_SUBCATEGORIA
WHERE NOME_SUBCATEGORIA IS NULL

--FULL (ANTI) JOIN -SE USA RARAMENTE-
SELECT 
	* 
FROM
	produtos
-------
SELECT 
	* 
FROM 
	SUBCATEGORIA
------
SELECT 
	PRODUTOS.ID_PRODUTO,
	PRODUTOS.NOME_PRODUTO,
	PRODUTOS.ID_SUBCATEGORIA,
	SUBCATEGORIA.NOME_SUBCATEGORIA
FROM
	PRODUTOS
FULL JOIN SUBCATEGORIA
ON PRODUTOS.ID_CATEGORIA = SUBCATEGORIA.ID_SUBCATEGORIA
WHERE ID_PRODUTO IS NULL OR NOME_SUBCATEGORIA IS NULL

-- EXEMPLO COM O CONTOSO--
SELECT 
	ProductKey,
	ProductName,
	DimProduct.ProductSubcategoryKey,
	ProductSubcategoryName
FROM
	DimProduct
INNER JOIN DimProductSubcategory
ON DimProduct. ProductSubcategoryKey= DimProductSubcategory.ProductSubcategoryKey

